//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Frycz_pcdb
{
    using System;
    using System.Collections.Generic;
    
    public partial class computer_parameters
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public computer_parameters()
        {
            this.computers = new HashSet<computer>();
        }
    
        public int idcomputer_parameters { get; set; }
        public string processor { get; set; }
        public Nullable<decimal> ram { get; set; }
        public Nullable<int> hdd { get; set; }
        public Nullable<bool> optical_disc_drive { get; set; }
        public Nullable<bool> external_gpu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<computer> computers { get; set; }
    }
}
