//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Frycz_pcdb
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class frycz_pcdbEntities : DbContext
    {
        public frycz_pcdbEntities()
            : base("name=frycz_pcdbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<computer> computers { get; set; }
        public virtual DbSet<computer_parameters> computer_parameters { get; set; }
        public virtual DbSet<computer_type> computer_type { get; set; }
        public virtual DbSet<department> departments { get; set; }
        public virtual DbSet<logging> loggings { get; set; }
        public virtual DbSet<o> os { get; set; }
        public virtual DbSet<registered_user> registered_user { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<computer_brand> computer_brand { get; set; }
    }
}
