//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace Frycz_pcdb
{
    using System;
    using System.Collections.Generic;
    
    public partial class logging
    {
        public int idlogging { get; set; }
        public string info { get; set; }
        public Nullable<System.DateTime> time { get; set; }
        public Nullable<int> idregistered_user { get; set; }
    
        public virtual registered_user registered_user { get; set; }
    }
}
